### ISSUE TITLE
Run.sh cannot be found when the integration test is executed

### ISSUE THREAD

**Issue by ben2077** [scylladb/java-driver#104]
java.lang.RuntimeException: The command '[/home/ben77/Projects/iqiyi/scylla-java-driver/integration-tests/run.sh]' failed to execute

	at com.datastax.oss.driver.api.core.cloud.SniProxyServer.execute(SniProxyServer.java:144)
	at com.datastax.oss.driver.api.core.cloud.SniProxyServer.startProxy(SniProxyServer.java:63)
	at com.datastax.oss.driver.api.core.cloud.SniProxyRule.before(SniProxyRule.java:30)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
**Caused by: java.io.IOException: Cannot run program "/home/ben77/Projects/iqiyi/scylla-java-driver/integration-tests/run.sh" (in directory "/home/ben77/Projects/iqiyi/scylla-java-driver/integration-tests"): error=2, No such file or directory**
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)

**Comment by haaawk** [comment]
Which branch is this @CodingBen ?
