### ISSUE TITLE
Why does he always access the internal ip of the container？and how can i solve it

### ISSUE THREAD

**Issue by TD-duanzhichao** [scylladb/java-driver#146]
I have a problem, when connecting to the cluster, the following error will be reported，

My scylladb images docker cluster is as follows
<img width="500" alt="WeChat97bd4261fefbb7863af5741a0c44f0ab" src="https://user-images.githubusercontent.com/107902748/180910956-24b0096b-e020-41c4-9421-a963ad1d7f65.png">

This is how I connect use driver：
![image](https://user-images.githubusercontent.com/107902748/180911258-7130e5b8-a1bc-4d15-ace4-f8bd6dd9f69b.png)
![image](https://user-images.githubusercontent.com/107902748/180911316-fb086cab-fc60-4cef-94a9-f4bbb0ca136c.png)

and error reported as follows:

2022-07-26 09:56:29.940  INFO 3401 --- [           main] com.datastax.driver.core.Cluster         : New Cassandra host scylla1/127.0.0.1:9042 added
2022-07-26 09:56:29.940  INFO 3401 --- [           main] com.datastax.driver.core.Cluster         : New Cassandra host /172.17.0.4:9042 added
2022-07-26 09:56:29.940  INFO 3401 --- [           main] com.datastax.driver.core.Cluster         : New Cassandra host /172.17.0.3:9042 added
2022-07-26 09:56:29.970  INFO 3401 --- [           main] c.d.driver.core.HostConnectionPool       : Using advanced port-based shard awareness with scylla1/127.0.0.1:9042
2022-07-26 09:56:29.995  WARN 3401 --- [r1-nio-worker-4] com.datastax.driver.core.Connection      : Advanced shard awareness: requested connection to shard 3, but connected to 0. Is there a NAT between client and server?
2022-07-26 09:56:35.031  WARN 3401 --- [r1-nio-worker-5] com.datastax.driver.core.Connection      : Error creating netty channel to /172.17.0.4:9042

io.netty.channel.ConnectTimeoutException: connection timed out: /172.17.0.4:9042
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2022-07-26 09:56:35.039  WARN 3401 --- [           main] com.datastax.driver.core.Session         : Error creating pool to /172.17.0.4:9042

com.datastax.driver.core.exceptions.TransportException: [/172.17.0.4:9042] Cannot connect
	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:320) ~[scylla-driver-core-3.11.2.0.jar:na]
	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:247) ~[scylla-driver-core-3.11.2.0.jar:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:262) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /172.17.0.4:9042
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	... 10 common frames omitted

2022-07-26 09:56:35.038 ERROR 3401 --- [uster1-worker-0] c.d.d.core.ExceptionCatchingRunnable     : Unexpected error while executing task

java.lang.NullPointerException: null
	at com.datastax.driver.core.HostConnectionPool.closeAsync(HostConnectionPool.java:966) ~[scylla-driver-core-3.11.2.0.jar:na]
	at com.datastax.driver.core.SessionManager.removePool(SessionManager.java:446) ~[scylla-driver-core-3.11.2.0.jar:na]
	at com.datastax.driver.core.SessionManager.onDown(SessionManager.java:534) ~[scylla-driver-core-3.11.2.0.jar:na]
	at com.datastax.driver.core.Cluster$Manager.onDown(Cluster.java:2285) ~[scylla-driver-core-3.11.2.0.jar:na]
	at com.datastax.driver.core.Cluster$Manager.access$1200(Cluster.java:1636) ~[scylla-driver-core-3.11.2.0.jar:na]
	at com.datastax.driver.core.Cluster$Manager$5.runMayThrow(Cluster.java:2240) ~[scylla-driver-core-3.11.2.0.jar:na]
	at com.datastax.driver.core.ExceptionCatchingRunnable.run(ExceptionCatchingRunnable.java:32) ~[scylla-driver-core-3.11.2.0.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) ~[guava-19.0.jar:na]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) ~[guava-19.0.jar:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) ~[guava-19.0.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2022-07-26 09:56:40.052  WARN 3401 --- [r1-nio-worker-9] com.datastax.driver.core.Connection      : Error creating netty channel to /172.17.0.3:9042

io.netty.channel.ConnectTimeoutException: connection timed out: /172.17.0.3:9042
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2022-07-26 09:56:40.059 ERROR 3401 --- [uster1-worker-1] c.d.d.core.ExceptionCatchingRunnable     : Unexpected error while executing task

java.lang.NullPointerException: null
	at com.datastax.driver.core.HostConnectionPool.closeAsync(HostConnectionPool.java:966) ~[scylla-driver-core-3.11.2.0.jar:na]
	at com.datastax.driver.core.SessionManager.removePool(SessionManager.java:446) ~[scylla-driver-core-3.11.2.0.jar:na]
	at com.datastax.driver.core.SessionManager.onDown(SessionManager.java:534) ~[scylla-driver-core-3.11.2.0.jar:na]
	at com.datastax.driver.core.Cluster$Manager.onDown(Cluster.java:2285) ~[scylla-driver-core-3.11.2.0.jar:na]
	at com.datastax.driver.core.Cluster$Manager.access$1200(Cluster.java:1636) ~[scylla-driver-core-3.11.2.0.jar:na]
	at com.datastax.driver.core.Cluster$Manager$5.runMayThrow(Cluster.java:2240) ~[scylla-driver-core-3.11.2.0.jar:na]
	at com.datastax.driver.core.ExceptionCatchingRunnable.run(ExceptionCatchingRunnable.java:32) ~[scylla-driver-core-3.11.2.0.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) ~[guava-19.0.jar:na]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) ~[guava-19.0.jar:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) ~[guava-19.0.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2022-07-26 09:56:40.064  WARN 3401 --- [           main] com.datastax.driver.core.Session         : Error creating pool to /172.17.0.3:9042

com.datastax.driver.core.exceptions.TransportException: [/172.17.0.3:9042] Cannot connect
	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:320) ~[scylla-driver-core-3.11.2.0.jar:na]
	at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:247) ~[scylla-driver-core-3.11.2.0.jar:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:262) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.75.Final.jar:4.1.75.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /172.17.0.3:9042
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) ~[netty-transport-4.1.75.Final.jar:4.1.75.Final]
	... 10 common frames omitted

**Comment by TD-duanzhichao** [comment]
and my scylladb driver version is 3.11.2.0
 <scylla.driver.version>3.11.2.0</scylla.driver.version>

![image](https://user-images.githubusercontent.com/107902748/180912466-ea0dcbe8-88aa-40c7-bc5f-964a31526309.png)
