### ISSUE TITLE
[serverless] connection should be only open with `server`

### ISSUE THREAD

**Issue by fruch** [scylladb/java-driver#164]
Running recent cassandra-stress (that uses java-driver with sni_proxy support)
with a local setup kind of scylla-operator 
```
docker run -it --network=host -v /home/fruch/Downloads/k8s_config.yaml:/k8s_config.yaml --entrypoint=/bin/bash scylladb/scylla-nightly cassandra-stress write -cloudconf file=/k8s_config.yaml -log interval=5
```

```
cat /etc/hosts

127.0.0.1       localhost
127.0.1.1       fruch-scylla

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

10.96.121.188 any.cql.fruch.scylladb.com
#10.96.121.188 c0e65e5c-38d1-431d-8e9f-d9dd5af9854f.cql.fruch.scylladb.com
#10.96.121.188 dd4e15e6-fcb0-46b1-af88-8a010a6161ed.cql.fruch.scylladb.com
#10.96.121.188 0d56abe0-91f9-43ee-9b39-4536488b6089.cql.fruch.scylladb.com
```

fails when it's trying to do DNS resolving of the nodes, which it shouldn't be doing, on the `any.cql.*` address should be connected to:
```

Connected to cluster: sct-cluster, max pending requests per connection null, max connections per host 8
java.lang.RuntimeException: java.lang.IllegalArgumentException: Could not resolve proxy address c0e65e5c-38d1-431d-8e9f-d9dd5af9854f.cql.fruch.scylladb.com
        at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:223)
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:79)
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
        at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:231)
        at org.apache.cassandra.stress.StressAction.run(StressAction.java:58)
        at org.apache.cassandra.stress.Stress.run(Stress.java:143)
        at org.apache.cassandra.stress.Stress.main(Stress.java:62)
Caused by: java.lang.IllegalArgumentException: Could not resolve proxy address c0e65e5c-38d1-431d-8e9f-d9dd5af9854f.cql.fruch.scylladb.com
        at com.datastax.driver.core.SniEndPoint.resolve(SniEndPoint.java:68)
        at com.datastax.driver.core.Host.getAddress(Host.java:196)
        at org.apache.cassandra.stress.util.JavaDriverClient.connect(JavaDriverClient.java:191)
        at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:214)
        ... 6 more
Caused by: java.net.UnknownHostException: c0e65e5c-38d1-431d-8e9f-d9dd5af9854f.cql.fruch.scylladb.com: Name or service not known
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1529)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1519)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1378)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at com.datastax.driver.core.SniEndPoint.resolve(SniEndPoint.java:55)
        ... 9 more
```

> We (@tnozicka) talked with 
@zimnx 
 and all traffic should go to the server. Contrary to or initial design, and to comply with meaning of the fields we have, the operator is not gonna use the any.cql.clusterName... prefix in the future but only cql.clusterName... for the load balanced endpoint. So technically only cql.clusterName... has to be resolvable. The infra will have it setup as a wildcard anyways.
This will make it be in line with how TLS.ServerName behaves. The change is to remove tlsServerName field from the config, that is fully covered in the nodeDomain field that acts as TLS.ServerName suffix. This won't need a driver change as it's only in the operator.

**Comment by avelanarius** [comment]
A fix is probably very easy:

```diff
diff --git a/driver-core/src/main/java/com/datastax/driver/core/ScyllaCloudSniEndPointFactory.java b/driver-core/src/main/java/com/datastax/driver/core/ScyllaCloudSniEndPointFactory.java
index a373dd9ab..0f90c5ef8 100644
--- a/driver-core/src/main/java/com/datastax/driver/core/ScyllaCloudSniEndPointFactory.java
+++ b/driver-core/src/main/java/com/datastax/driver/core/ScyllaCloudSniEndPointFactory.java
@@ -39,7 +39,7 @@ class ScyllaCloudSniEndPointFactory implements EndPointFactory {
   public EndPoint create(Row row) {
     UUID host_id = row.getUUID("host_id");
     String sni = host_id.toString() + "." + nodeDomain;
-    InetSocketAddress proxy = InetSocketAddress.createUnresolved(sni, port);
+    InetSocketAddress proxy = InetSocketAddress.createUnresolved(nodeDomain, port);
     return new SniEndPoint(proxy, sni);
   }
 }
```

but I'll double check if it really works and is really correct.
