### ISSUE TITLE
[serverless] should connect to Server specified in ConnectionConfig and use NodeDomain as SNI.

### ISSUE THREAD

**Issue by fruch** [scylladb/java-driver#167]
with this configuration:
```yaml
...
datacenters:
  dc-1:
    certificateAuthorityData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZHakNDQXdLZ0F3SUJBZ0lRZEJ3R1p4a1JKdG5jc01uN2R3eXBJVEFOQmdrcWhraUc5dzBCQVEwRkFEQW4KTVNVd0l3WURWUVFERXh4elkzUXRZ>
    nodeDomain: cql.sct-cluster.sct.scylladb.com
    server: 10.92.10.33:9142
...
```

we are failing like the following:
```
DEBUG    RemoteCmdRunner:base.py:150 STDERR: WARN  13:41:57,068 Error creating netty channel to 10.96.30.25:9142:10.96.30.25
com.datastax.shaded.netty.channel.ConnectTimeoutException: connection timed out: /10.96.30.25:9142
	at com.datastax.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	at com.datastax.shaded.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at com.datastax.shaded.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at com.datastax.shaded.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at com.datastax.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.RuntimeException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: 10.96.30.25:9142:10.96.30.25 (com.datastax.driver.core.exceptions.TransportException: [10.96.30.25:9142:10.96.30.25] Cannot connect))
	at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:223)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:79)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
	at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:231)
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:58)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: 10.96.30.25:9142:10.96.30.25 (com.datastax.driver.core.exceptions.TransportException: [10.96.30.25:9142:10.96.30.25] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:275)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:114)
	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1843)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1757)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:475)
	at org.apache.cassandra.stress.util.JavaDriverClient.connect(JavaDriverClient.java:182)
	at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:214)
	... 6 more
```

Instead it should connect to Server specified in ConnectionConfig and use NodeDomain as SNI.

See PRs in the other driver to align on how we want it to behave:
https://github.com/scylladb/python-driver/pull/177
https://github.com/scylladb/gocql/pull/106

**Comment by fruch** [comment]
@avelanarius would you able to have someone looking into it ?

**Comment by avelanarius** [comment]
@fruch Yes, I'll look into it (and #164 too).
