### ISSUE TITLE
Driver sometimes connects to "any.cluster-id.scylla.com" endpoint in integration tests

### ISSUE THREAD

**Issue by avelanarius** [scylladb/java-driver#169]
```
    29877  [cluster1-nio-worker-0] WARN  com.datastax.driver.core.Connection - Error creating netty channel to any.cluster-id.scylla.com:35617:any.cluster-id.scylla.com
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: Brak trasy do hosta: any.cluster-id.scylla.com/185.100.131.102:35617
Caused by: java.net.NoRouteToHostException: Brak trasy do hosta
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by avelanarius** [comment]
The reason is that we leave `any.cluster-id.scylla.com` in contact points (and add a real contact point, without removing `any.cluster-id.scylla.com`).

**Comment by fruch** [comment]
> The reason is that we leave `any.cluster-id.scylla.com` in contact points (and add a real contact point, without removing `any.cluster-id.scylla.com`).

It was a real painful part in the python-driver.
