### ISSUE TITLE
Don't limit `scylla.version` to actual version number 

### ISSUE THREAD

**Issue by fruch** [scylladb/java-driver#217]
there are cases we want to use CCM with non-released versions, like:
```
unstable/master:latest
13812adsaf # version crafted from a local unified package, and uses scylla sha, this is how it in all places we run in jenkins: dtest/python-matrix and such
```
```

and this break the following code paths:
```
installArgs.add("-v release:" + inputScyllaVersion);
...
GLOBAL_SCYLLA_VERSION_NUMBER = VersionNumber.parse(inputScyllaVersion);
```

**Comment by fruch** [comment]
I'll share the example of how to get an actual version sting out of CCM, without running a version

**Comment by fruch** [comment]
so basically we need to run this with the version (it would download and cache it, for next cluster it create)
```bash
❯ ccm create get_version -n 1 --scylla --version unstable/master:latest
Current cluster is now: get_version
❯ ccm node1 versionfrombuild
5.4.0-dev
❯ ccm remove
```

**Comment by fruch** [comment]
It's depend on this CCM fix, to work without starting a node: https://github.com/scylladb/scylla-ccm/pull/458

**Comment by avelanarius** [comment]
@k0machi isn't this already fixed in matrix tests?

**Comment by fruch** [comment]
> @k0machi isn't this already fixed in matrix tests?

No, patched and hardcoded it to some number for now.

**Comment by Bouncheck** [comment]
@fruch what is the correct syntax for hash versions? I tried the following, but it does not seem to work:
```
[wo@fedora java-driver]$ ccm create get_version -n 1 --scylla --version b87fb94a5efeb496a9d60947346c334bb3c40f58
Traceback (most recent call last):
  File "/home/wo/.local/bin/ccm", line 74, in <module>
    cmd.run()
  File "/home/wo/.local/lib/python3.11/site-packages/ccmlib/cmds/cluster_cmds.py", line 220, in run
    cluster = ScyllaCluster(self.path, self.name, install_dir=self.options.install_dir,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wo/.local/lib/python3.11/site-packages/ccmlib/scylla_cluster.py", line 53, in __init__
    super(ScyllaCluster, self).__init__(path, name, partitioner,
  File "/home/wo/.local/lib/python3.11/site-packages/ccmlib/cluster.py", line 72, in __init__
    dir, v = self.load_from_repository(version, verbose)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wo/.local/lib/python3.11/site-packages/ccmlib/scylla_cluster.py", line 74, in load_from_repository
    install_dir, version = scylla_repository.setup(version, verbose)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wo/.local/lib/python3.11/site-packages/ccmlib/scylla_repository.py", line 381, in setup
    package_version, packages = download_packages(version_dir=version_dir, packages=packages, s3_url=s3_url,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wo/.local/lib/python3.11/site-packages/ccmlib/scylla_repository.py", line 439, in download_packages
    package_version = download_version(version=version, verbose=verbose, url=packages.scylla_package,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wo/.local/lib/python3.11/site-packages/ccmlib/scylla_repository.py", line 508, in download_version
    if os.path.exists(url) and url.endswith('.tar.gz'):
       ^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

```

**Comment by fruch** [comment]
> @fruch what is the correct syntax for hash versions? I tried the following, but it does not seem to work:
> ```
> [wo@fedora java-driver]$ ccm create get_version -n 1 --scylla --version b87fb94a5efeb496a9d60947346c334bb3c40f58
> Traceback (most recent call last):
>   File "/home/wo/.local/bin/ccm", line 74, in <module>
>     cmd.run()
>   File "/home/wo/.local/lib/python3.11/site-packages/ccmlib/cmds/cluster_cmds.py", line 220, in run
>     cluster = ScyllaCluster(self.path, self.name, install_dir=self.options.install_dir,
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/wo/.local/lib/python3.11/site-packages/ccmlib/scylla_cluster.py", line 53, in __init__
>     super(ScyllaCluster, self).__init__(path, name, partitioner,
>   File "/home/wo/.local/lib/python3.11/site-packages/ccmlib/cluster.py", line 72, in __init__
>     dir, v = self.load_from_repository(version, verbose)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/wo/.local/lib/python3.11/site-packages/ccmlib/scylla_cluster.py", line 74, in load_from_repository
>     install_dir, version = scylla_repository.setup(version, verbose)
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/wo/.local/lib/python3.11/site-packages/ccmlib/scylla_repository.py", line 381, in setup
>     package_version, packages = download_packages(version_dir=version_dir, packages=packages, s3_url=s3_url,
>                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/wo/.local/lib/python3.11/site-packages/ccmlib/scylla_repository.py", line 439, in download_packages
>     package_version = download_version(version=version, verbose=verbose, url=packages.scylla_package,
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/wo/.local/lib/python3.11/site-packages/ccmlib/scylla_repository.py", line 508, in download_version
>     if os.path.exists(url) and url.endswith('.tar.gz'):
>        ^^^^^^^^^^^^^^^^^^^
>   File "<frozen genericpath>", line 19, in exists
> TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
> 
> ```

Use:
unstable/master:latest

The version can be any string, and hash is used in Jenkins, when files were retrieved not by ccm, anyone can name a version how they want (it's just the directory where ccm puts the files)

If we want to assume anything about a version, we can expose the needed things as a ccm command (python driver calls those API directly)

**Comment by Bouncheck** [comment]
I understand now, thanks.

**Comment by Bouncheck** [comment]
Should be now resolved by #417 and #396
