### ISSUE TITLE
[3.x] ScyllaSniProxyTest  tests are failing 

### ISSUE THREAD

**Issue by fruch** [scylladb/java-driver#221]
one of the test assertion doesn't seem to be correct anymore and failing:

```
assert host.getEndPoint().resolve().getPort() == ccm().getSniPort();
```

```
20:14:46  [ERROR] com.datastax.driver.core.ScyllaSniProxyTest.test_ccm_cluster_1node  Time elapsed: 0.028 s  <<< FAILURE!
20:14:46  java.lang.AssertionError
20:14:46  	at com.datastax.driver.core.ScyllaSniProxyTest.test_ccm_cluster(ScyllaSniProxyTest.java:32)
20:14:46  	at com.datastax.driver.core.ScyllaSniProxyTest.test_ccm_cluster_1node(ScyllaSniProxyTest.java:68)
20:14:46  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:14:46  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:14:46  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:14:46  	at java.lang.reflect.Method.invoke(Method.java:498)
20:14:46  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
20:14:46  	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
20:14:46  	at org.jboss.byteman.contrib.bmunit.BMNGAbstractRunner.run(BMNGAbstractRunner.java:56)
20:14:46  	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
20:14:46  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:14:46  	at java.lang.reflect.Method.invoke(Method.java:498)
20:14:46  	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
20:14:46  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
20:14:46  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
20:14:46  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
20:14:46  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
20:14:46  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
20:14:46  	at org.testng.TestRunner.privateRun(TestRunner.java:767)
20:14:46  	at org.testng.TestRunner.run(TestRunner.java:617)
20:14:46  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
20:14:46  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
20:14:46  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
20:14:46  	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
20:14:46  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
20:14:46  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
20:14:46  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
20:14:46  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
20:14:46  	at org.testng.TestNG.run(TestNG.java:1057)
20:14:46  	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
20:14:46  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)
20:14:46  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)
20:14:46  	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
20:14:46  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
20:14:46  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
20:14:46  	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
20:14:46  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
```

and `test_ccm_cluster_3node` timeout on waiting for nodes up:
```
20:14:46  [ERROR] com.datastax.driver.core.ScyllaSniProxyTest.test_ccm_cluster_3node  Time elapsed: 60.059 s  <<< FAILURE!
20:14:46  java.lang.AssertionError: Timeout after 60 seconds while waiting for condition
20:14:46  	at com.datastax.driver.core.ConditionChecker.await(ConditionChecker.java:152)
20:14:46  	at com.datastax.driver.core.ConditionChecker$ConditionCheckerBuilder.becomesTrue(ConditionChecker.java:102)
20:14:46  	at com.datastax.driver.core.TestUtils.waitFor(TestUtils.java:586)
20:14:46  	at com.datastax.driver.core.TestUtils.waitForUp(TestUtils.java:550)
20:14:46  	at com.datastax.driver.core.ScyllaSniProxyTest.test_ccm_cluster(ScyllaSniProxyTest.java:24)
20:14:46  	at com.datastax.driver.core.ScyllaSniProxyTest.test_ccm_cluster_3node(ScyllaSniProxyTest.java:58)
20:14:46  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:14:46  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:14:46  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:14:46  	at java.lang.reflect.Method.invoke(Method.java:498)
20:14:46  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
20:14:46  	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
20:14:46  	at org.jboss.byteman.contrib.bmunit.BMNGAbstractRunner.run(BMNGAbstractRunner.java:56)
20:14:46  	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
20:14:46  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:14:46  	at java.lang.reflect.Method.invoke(Method.java:498)
20:14:46  	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
20:14:46  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
20:14:46  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
20:14:46  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
20:14:46  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
20:14:46  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
20:14:46  	at org.testng.TestRunner.privateRun(TestRunner.java:767)
20:14:46  	at org.testng.TestRunner.run(TestRunner.java:617)
20:14:46  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
20:14:46  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
20:14:46  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
20:14:46  	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
20:14:46  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
20:14:46  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
20:14:46  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
20:14:46  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
20:14:46  	at org.testng.TestNG.run(TestNG.java:1057)
20:14:46  	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
20:14:46  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)
20:14:46  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)
20:14:46  	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
20:14:46  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
20:14:46  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
20:14:46  	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
20:14:46  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
```

**Comment by Bouncheck** [comment]
I've looked at it recently and it seems that even though `--sni-port` flag is used, the port in config_data.yaml (serverless connection bundle) is 9142 no matter what was picked. I recall that there were slight changes to bundle structure some time ago, did `--sni-port` change too?

Relevant piece of config_data.yaml:
```
datacenters:
  datacenter1:
    certificateAuthorityData: LS0 [...] 0K
    server: 127.0.1.3:9142
    nodeDomain: cql.cluster-id.scylla.com
    insecureSkipTlsVerify: false
```
Example failed run:
https://github.com/scylladb/java-driver/actions/runs/4977897524/jobs/8911821088
```
 2013259 [main] INFO  com.datastax.driver.core.CCMBridge - Executing: ccm create ccm_22 -i 127.0.1.  -n 1  --scylla  -v release:5.1.9 --config-dir=/tmp/1684152016058-0
    2013704 [main] INFO  com.datastax.driver.core.TestUtils - Found available port: 39893
    2013705 [main] INFO  com.datastax.driver.core.CCMBridge - Executing: ccm updateconf start_rpc:false native_shard_aware_transport_port:44347 rpc_port:40607 prometheus_port:46339 storage_port:43991 api_port:38615 native_transport_port:32867  --config-dir=/tmp/1684152016058-0
    2014121 [main] INFO  com.datastax.driver.core.CCMBridge - Executing: ccm start  --sni-proxy --sni-port 34171 --config-dir=/tmp/1684152016058-0
    
 [...] stuff ommitted for brevity
 -----------------------------------------------
Starting com.datastax.driver.core.ScyllaSniProxyTest.test_ccm_cluster_1node [Test #464]...
    2047634 [main] WARN  com.datastax.driver.core.HostConnectionPool - Not using advanced port-based shard awareness with 127.0.1.1:9142:1dbf6eb8-cfc9-4c2a-9351-01db7f09c93a.cql.cluster-id.scylla.com because it's disabled in configuration
org.junit.ComparisonFailure: expected:<[34171]> but was:<[9142]>
FAILED : test_ccm_cluster_1node
Test   : 00:00:00
Elapsed: 00:34:08

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.datastax.driver.core.ScyllaSniProxyTest.test_ccm_cluster(ScyllaSniProxyTest.java:34)
	at com.datastax.driver.core.ScyllaSniProxyTest.test_ccm_cluster_1node(ScyllaSniProxyTest.java:115)
```

**Comment by fruch** [comment]
There were changes for supporting rust testing of multiple DC setup...

Could some of them break it...
