### ISSUE TITLE
[Scylla-5.2] `should_call_onAdd_with_bootstrap_stop_start` test started failing using `3.11.5.2` and `3.11.4.0` versions

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/java-driver#292]
Running the [scylla-5.2/driver-tests/java-driver-matrix-test#38](https://argus.scylladb.com/test/688b82d4-ad53-4e40-bcd1-fc77b007e84c/runs?additionalRuns[]=42d32e9d-3f20-4b8c-b400-728e8812f894) CI job the `should_call_onAdd_with_bootstrap_stop_start` test failed using `3.11.5.2` and `3.11.4.0` versions:

```
should_call_onAdd_with_bootstrap_stop_start
3.11.5.2.com.datastax.driver.core.NodeRefreshDebouncerTest

Wanted but not invoked:
stateListener.onAdd(<Capturing argument>);
-> at com.datastax.driver.core.NodeRefreshDebouncerTest.should_call_onAdd_with_bootstrap_stop_start(NodeRefreshDebouncerTest.java:63)

However, there were other interactions with this mock:
stateListener.onRegister(
    com.datastax.driver.core.Cluster@3d65fbab
);
-> at com.datastax.driver.core.Cluster.register(Cluster.java:518)

stateListener.onUp(/127.0.1.2:43329);
-> at com.datastax.driver.core.Cluster$Manager.onUp(Cluster.java:2127)

 (Wanted but not invoked)
```

Screenshot:
![Screenshot from 2024-04-22 13-53-10](https://github.com/scylladb/scylla-java-driver-matrix/assets/3796058/53aace7b-e42c-4380-a6de-a1d10c5f52a3)

This test doesn't fail using `master` scylla in latest runs.

**Comment by k0machi** [comment]
Unable to reproduce the issue locally - test succeds both on the unstable archive provided and the previous version - maybe test itself is flaky?

**Comment by vponomaryov** [comment]
> Unable to reproduce the issue locally - test succeds both on the unstable archive provided and the previous version - maybe test itself is flaky?

The failure happens using latest `5.2` scylla. Did you try it out?

**Comment by k0machi** [comment]
> > Unable to reproduce the issue locally - test succeds both on the unstable archive provided and the previous version - maybe test itself is flaky?
> 
> The failure happens using latest `5.2` scylla. Did you try it out?

Yes, I've tried the version that was in the run you've linked, and we also re-ran jenkins job for 5.2 and it seems [it didn't fail this time](https://argus.scylladb.com/test/688b82d4-ad53-4e40-bcd1-fc77b007e84c/runs?additionalRuns[]=56877a3d-3e5e-4c39-8135-db22c63118a2). I think the reason here is that the test has a configured timeout and the instance provided sometimes exceeds it - default value for the timeout is 1 second, haven't yet checked what the driver is built with however.

**Comment by vponomaryov** [comment]
Reproduced once again: [scylla-5.2/driver-tests/java-driver-matrix-test#40](https://argus.scylladb.com/test/688b82d4-ad53-4e40-bcd1-fc77b007e84c/runs?additionalRuns[]=30f387d6-5ac6-4d6a-8b8c-bfb12120b1b1)
