### ISSUE TITLE
3.x: there is some case when driver does not release `DefaultResultSetFuture` properly

### ISSUE THREAD

**Issue by dkropachev** [scylladb/java-driver#365]
It comes from https://github.com/scylladb/cassandra-stress/issues/30.
Time to time it can stuck waiting for `DefaultResultSetFuture` to be released:
```
"Thread-2" prio=5 Id=59 WAITING on com.datastax.driver.core.DefaultResultSetFuture@2ad5ebfd
  at java.base@11.0.25/jdk.internal.misc.Unsafe.park(Native Method)
  -  waiting on com.datastax.driver.core.DefaultResultSetFuture@2ad5ebfd
  at java.base@11.0.25/java.util.concurrent.locks.LockSupport.park(Unknown Source)
  at app//com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:561)
  at app//com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:247)
  at app//com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:308)
  at app//com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
  at app//org.apache.cassandra.stress.util.JavaDriverClient.executePrepared(JavaDriverClient.java:247)
  at app//org.apache.cassandra.stress.operations.predefined.CqlOperation$JavaDriverWrapper.execute(CqlOperation.java:308)

```

It means that there is a bug in `ReleaseHandler` or in `DefaultResultSetFuture` that leaves `DefaultResultSetFuture` without `set` or `setException` called on it.
As result `getUninterruptibly` waits for it forever.
to go forward we need to do the following:
1. Check `ReleaseHandler` and `DefaultResultSetFuture` to make sure every case ends up in `set` or `setException`
2. Find a way for `AbstractSession.execute(Statement statement)` to have timeout on `getUninterruptibly`.

**Comment by roydahan** [comment]
@dkropachev why is it still in "NEW"?
Shall we queue it and prioritize it for work?
I saw it affects at least 1-2 CI stability issues.

**Comment by dkropachev** [comment]
> [@dkropachev](https://github.com/dkropachev) why is it still in "NEW"? Shall we queue it and prioritize it for work? I saw it affects at least 1-2 CI stability issues.

There was lots of work done to pin point the issue, unfortunately it was pushed out by other higher priority tasks.
I have scheduled it for next sprint.

**Comment by roydahan** [comment]
@dkropachev , @Bouncheck,
This issue translates into CI stability issues (Through https://github.com/scylladb/cassandra-stress/issues/30) and IIUC correctly a customer issue.
Hence, this issue should have higher (highest?) priority this week/next week.

**Comment by dkropachev** [comment]
I will prioritize it this week.

**Comment by roydahan** [comment]
@dkropachev & @nikagra I think it's time to fix this set of issues with java 3.x and get rid of these ci-stability issues.

**Comment by nikagra** [comment]
@dkropachev
> Check `ReleaseHandler` and `DefaultResultSetFuture` to make sure every case ends up in `set` or `setException`

Checking `DefaultResultSetFuture.onSet` method:
- ✅ `RESULT`
  - ✅ `SET_KEYSPACE` (direct call to `set`)
  - ✅ `SCHEMA_CHANGE` 
    - ✅ If `!cluster.configuration.getQueryOptions().isMetadataEnabled()` (indirectly via `cluster.waitForSchemaAgreementAndSignal`)
    - ✅ For `CREATED` or `UPDATED` (indirectly via `cluster.refreshSchemaAndSignal`)
    - ✅ For `DROPPED` case (indirectly via `session.cluster.manager.waitForSchemaAgreementAndSignal`
    - ⚠️ `default` case does not set any result or exception
  - ✅ `default` case (direct call to `set`)
- ✅ `ERROR` (direct call to `setException`)
- ✅ `default` (direct call to `setException`)
- ✅ catch block ( direct call to `setException`)

So, unknown schema change may result in no result set in the future.

> Find a way for `AbstractSession.execute(Statement statement)` to have timeout on `getUninterruptibly`.

`DefaultResultSetFuture` already have an overloaded version of `getUninterruptibly` handling timeouts:
```java
  @Override
  public ResultSet getUninterruptibly(long timeout, TimeUnit unit) throws TimeoutException {
    try {
      return Uninterruptibles.getUninterruptibly(this, timeout, unit);
    } catch (ExecutionException e) {
      throw DriverThrowables.propagateCause(e);
    }
  }
```

**Comment by dkropachev** [comment]
> [@dkropachev](https://github.com/dkropachev)
> 
> > Check `ReleaseHandler` and `DefaultResultSetFuture` to make sure every case ends up in `set` or `setException`
> 
> Checking `DefaultResultSetFuture.onSet` method:
> 
> * ✅ `RESULT`
>   
>   * ✅ `SET_KEYSPACE` (direct call to `set`)
>   * ✅ `SCHEMA_CHANGE`
>     
>     * ✅ If `!cluster.configuration.getQueryOptions().isMetadataEnabled()` (indirectly via `cluster.waitForSchemaAgreementAndSignal`)
>     * ✅ For `CREATED` or `UPDATED` (indirectly via `cluster.refreshSchemaAndSignal`)
>     * ✅ For `DROPPED` case (indirectly via `session.cluster.manager.waitForSchemaAgreementAndSignal`
>     * ⚠️ `default` case does not set any result or exception
>   * ✅ `default` case (direct call to `set`)
> * ✅ `ERROR` (direct call to `setException`)
> * ✅ `default` (direct call to `setException`)
> * ✅ catch block ( direct call to `setException`)
> 
> So, unknown schema change may result in no result set in the future.
> 

I did not check on it, but I 100% sure that the following is not true:
>     * ⚠️ `default` case does not set any result or exception

> > Find a way for `AbstractSession.execute(Statement statement)` to have timeout on `getUninterruptibly`.
> 
> `DefaultResultSetFuture` already have an overloaded version of `getUninterruptibly` handling timeouts:
> 
>   @Override
>   public ResultSet getUninterruptibly(long timeout, TimeUnit unit) throws TimeoutException {
>     try {
>       return Uninterruptibles.getUninterruptibly(this, timeout, unit);
>     } catch (ExecutionException e) {
>       throw DriverThrowables.propagateCause(e);
>     }
>   }

Great, now we need to make use of it in `AbstractSession.execute`

**Comment by dkropachev** [comment]
> > So, unknown schema change may result in no result set in the future.
> 
> I did not check on it, but I 100% sure that the following is not true:
> 
> > ```
> > * ⚠️ `default` case does not set any result or exception
> > ```

It looks like I have been looking at another default, you are correct there.
Did you check the process when driver drops DefaultResultSetFuture, it should throw stop an timeout timer and either call onException or onTimeout ? My guess that problem should be somewhere there.

**Comment by dkropachev** [comment]
Finaly it is fixed in https://github.com/scylladb/java-driver/pull/794, wait for new release
