### ISSUE TITLE
4.x: RemovedNodeIT.should_signal_and_destroy_pool_when_node_gets_removed can fail

### ISSUE THREAD

**Issue by dkropachev** [scylladb/java-driver#393]
Run: https://github.com/scylladb/java-driver/actions/runs/11936102649/job/33268985504?pr=373
Stack trace:
```
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 41.431 s <<< FAILURE! - in com.datastax.oss.driver.core.session.RemovedNodeIT
Error:  com.datastax.oss.driver.core.session.RemovedNodeIT.should_signal_and_destroy_pool_when_node_gets_removed  Time elapsed: 0.216 s  <<< FAILURE!
java.lang.AssertionError: 

Expected size: 4 but was: 3 in:
[Murmur3TokenRange(Murmur3Token(-9223372036854775808), Murmur3Token(-9223372036854775708)),
    Murmur3TokenRange(Murmur3Token(-9223372036854775708), Murmur3Token(1985283325061293259)),
    Murmur3TokenRange(Murmur3Token(1985283325061293259), Murmur3Token(-9223372036854775808))]
	at com.datastax.oss.driver.core.session.RemovedNodeIT.should_signal_and_destroy_pool_when_node_gets_removed(RemovedNodeIT.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:95)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

**Comment by Bouncheck** [comment]
(Logs below are from cassandra-java-driver 4.19.0 and Cassandra 4.0 IIRC)

This happens when one of the nodes starts without owning any unique tokens. It seems to be random, but not that rare.
When it occurs the following logs can be found on the node (node3 in this case):
```
INFO  [main] 2025-02-28 14:03:59,781 StorageService.java:2737 - Node /127.0.0.3:7000 state jump to NORMAL
INFO  [main] 2025-02-28 14:03:59,783 Gossiper.java:2171 - Waiting for gossip to settle...
INFO  [GossipStage:1] 2025-02-28 14:04:00,743 StorageService.java:2707 - Nodes /127.0.0.4:7000 and /127.0.0.3:7000 hav
e the same token 1985283325061293259.  Ignoring /127.0.0.4:7000
```
Besides that the node looks to be healthy.

On the driver side it seems that the `system_peers` or `system_peers_v2` row corresponding to node3 ends up having `tokens` column `null`, therefore considered as invalid peer. All of that results in initially seeing only 3 distinct values when assertion is run.
```
14:04:09.106 [s0-io-2] WARN  c.d.o.d.i.c.m.DefaultTopologyMonitor - [s0] Found invalid row in system.peers_v2 for peer: /127.0.0.3. This is likely a gossip or snitch issue, this node will be ignored.
...
14:04:09.110 [s0-admin-0] DEBUG c.d.o.d.i.c.metadata.DefaultMetadata - [s0] Building initial token map
14:04:09.112 [s0-admin-0] DEBUG c.d.o.d.i.c.m.token.DefaultTokenMap - [s0] Rebuilt ring (3 tokens)
14:04:09.119 [s0-admin-0] DEBUG c.d.o.d.i.c.m.token.DefaultTokenMap - [s0] Computing keyspace-level data for {}
14:04:09.119 [s0-admin-0] DEBUG c.d.o.d.i.c.metadata.DefaultMetadata - [s0] Rebuilding token map took 9 ms
```
This raises the question:
Is it a bug in scylla-ccm that the cluster starts in such state, or is it normal behavior that should be handled by the test?

**Comment by roydahan** [comment]
> (Logs below are from cassandra-java-driver 4.19.0 and Cassandra 4.0 IIRC)
> 
> This happens when one of the nodes starts without owning any unique tokens. It seems to be random, but not that rare. When it occurs the following logs can be found on the node (node3 in this case):
> 

> This raises the question: Is it a bug in scylla-ccm that the cluster starts in such state, or is it normal behavior that should be handled by the test?

That's weird, @fruch is it something that can happen from the "fast start" of ccm?

**Comment by fruch** [comment]
> > (Logs below are from cassandra-java-driver 4.19.0 and Cassandra 4.0 IIRC)
> > This happens when one of the nodes starts without owning any unique tokens. It seems to be random, but not that rare. When it occurs the following logs can be found on the node (node3 in this case):
> 
> > This raises the question: Is it a bug in scylla-ccm that the cluster starts in such state, or is it normal behavior that should be handled by the test?
> 
> That's weird, [@fruch](https://github.com/fruch) is it something that can happen from the "fast start" of ccm?

can the configuration yaml be shared ?

**Comment by mykaul** [comment]
I remember an issue (below) where system.peers was not fully populated, and there was some issue with it, not peers_v2 is a Cassandra table, so that's something else, I reckon: 

commit 3815f534eca5c33a611d70a16fcee38715f4d6a5
Author: Piotr Grabowski <piotr.grabowski@scylladb.com>
Date:   Fri Mar 1 16:45:04 2024 +0100

    cluster: improve logging of peers row validation
    
    Before this change, when the driver received an invalid system.peers row
    it would log a very general warning:
    
        Found an invalid row for peer (127.0.73.5). Ignoring host.
    
    A system.peers row can be invalid for a multitude of reasons and that
    warning message did not describe the specific reason for the failure.
    
    Improve the warning message by adding a specific reason why the row
    is considered invalid by the driver. The message now also includes
    the host_id or the entire row (in case the driver received a row
    without even the basic broadcast_rpc).
    
    It might be a bit inelegant to introduce a side effect (logging) to
    the _is_valid_peer static method, however the alternative solution seemed
    even worse - adding that code to the already big
    _refresh_node_list_and_token_map.
    
    Fixes #303

**Comment by Bouncheck** [comment]
> > > (Logs below are from cassandra-java-driver 4.19.0 and Cassandra 4.0 IIRC)
> > > This happens when one of the nodes starts without owning any unique tokens. It seems to be random, but not that rare. When it occurs the following logs can be found on the node (node3 in this case):
> > 
> > 
> > > This raises the question: Is it a bug in scylla-ccm that the cluster starts in such state, or is it normal behavior that should be handled by the test?
> > 
> > 
> > That's weird, [@fruch](https://github.com/fruch) is it something that can happen from the "fast start" of ccm?
> 
> can the configuration yaml be shared ?

@fruch 
[RemovedNodeIT_logs_gh.zip](https://github.com/user-attachments/files/19054298/RemovedNodeIT_logs_gh.zip)
Attached driver logs too

**Comment by fruch** [comment]
seem like cause of 
https://github.com/scylladb/java-driver/blame/663064f7888f13e8af0ddefc29764c8a1c23283e/test-infra/src/main/java/com/datastax/oss/driver/api/testinfra/ccm/CcmBridge.java#L373

all nodes are configured like that:
```
initial_token: -9223372036854775808
```

maybe it case to overlap, which exclude one node ?

is this test ever worked ? does it work with upstream ccm ? (https://github.com/riptano/ccm)

this test works on the upstream driver ?

**Comment by Bouncheck** [comment]
> seem like cause of https://github.com/scylladb/java-driver/blame/663064f7888f13e8af0ddefc29764c8a1c23283e/test-infra/src/main/java/com/datastax/oss/driver/api/testinfra/ccm/CcmBridge.java#L373
> 

I don't follow why

> all nodes are configured like that:
> 
> ```
> initial_token: -9223372036854775808
> ```
> 
> maybe it case to overlap, which exclude one node ?
> 
> is this test ever worked ? does it work with upstream ccm ? (https://github.com/riptano/ccm)

I think it has been flaky for a long time. With upstream ccm (and cassandra-java-driver 4.19.0, C* 4.0.0) it looks pretty stable. No failures so far (>80 counted runs)

> this test works on the upstream driver ?

cassandra-java-driver on upstream CI seems not to have a problem with this test. Recently it failed once, but ccm failed to start altogether there which is a different issue.


cassandra-java-driver, 4.19.0, cassandra 4.0.0, scylla-ccm (months old, unspecified version, possibly 2.0.5): Passes and fails with the same reason as in this issue. This time i had to run it multiple times until it failed. Less than 20 times, i don't remember exact number.

scylladb/java-driver, scylla-4.x branch, Scylla 6.2.0, scylla-ccm (months old): seems to consistently pass

2 different failures on our CI seem to both fail with Cassandra 4.x versions (one of them being 4.1.7)

**Comment by dkropachev** [comment]
Fix: https://github.com/scylladb/scylla-ccm/pull/643
