### ISSUE TITLE
Stress command completed with bad status 1 during nodetool drain command

### ISSUE THREAD

**Issue by timtimb0t** [scylladb/java-driver#397]
## Packages

Scylla version: `2024.2.1-20241202.3006adf5a31c` with build-id `342fea135a307bc12f58d4b203c8d7f50aad6b9a`

Kernel Version: `5.15.0-1072-aws`

## Issue description
New issue

During running nodetool drain command driver raised the following exception:
```
2024-12-03 02:46:46.430: (CassandraStressEvent Severity.CRITICAL) period_type=end event_id=500a197e-1276-48d0-97dc-ff64437007e5 during_nemesis=CreateIndex duration=12h0m4s: node=Node longevity-parallel-topology-schema--loader-node-b6114284-2 [3.208.185.250 | 10.12.10.199]
stress_cmd=cassandra-stress read  cl=QUORUM duration=720m -schema 'replication(strategy=NetworkTopologyStrategy,replication_factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -mode cql3 native -rate 'threads=40 throttle=15000/s' -pop 'dist=uniform(1..20971520)' -col 'n=FIXED(10) size=FIXED(128)' -log interval=10 -errors 'retries=30'
errors:
Stress command completed with bad status 1: Failed to connect over JMX; not collecting these stats
com.datastax.driver.core.exceptions.Transport
```

## Impact

Unclear, scylla is alive but driver raised critical exception

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 5 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-parallel-topology-schema--db-node-b6114284-9 (100.25.27.20 | 10.12.8.148) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-8 (54.157.86.44 | 10.12.10.4) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-7 (98.85.88.253 | 10.12.9.192) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-6 (3.95.49.50 | 10.12.8.183) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-5 (35.174.149.136 | 10.12.11.60) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-4 (52.5.37.87 | 10.12.9.76) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-30 (34.236.28.167 | 10.12.11.244) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-3 (98.85.198.142 | 10.12.10.237) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-29 (3.82.135.109 | 10.12.9.63) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-28 (52.71.17.176 | 10.12.11.197) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-27 (52.204.79.196 | 10.12.11.10) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-26 (3.227.39.16 | 10.12.11.242) (shards: -1)
- longevity-parallel-topology-schema--db-node-b6114284-25 (100.26.78.253 | 10.12.8.160) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-24 (18.233.33.66 | 10.12.9.123) (shards: -1)
- longevity-parallel-topology-schema--db-node-b6114284-23 (44.199.83.4 | 10.12.11.247) (shards: -1)
- longevity-parallel-topology-schema--db-node-b6114284-22 (54.158.34.188 | 10.12.10.153) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-21 (3.219.186.37 | 10.12.11.146) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-20 (52.206.189.86 | 10.12.10.174) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-2 (44.198.128.32 | 10.12.10.193) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-19 (44.196.132.198 | 10.12.8.125) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-18 (23.21.41.110 | 10.12.11.167) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-17 (50.19.131.110 | 10.12.9.18) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-16 (3.222.53.239 | 10.12.8.44) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-15 (54.144.246.30 | 10.12.11.128) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-14 (34.199.254.238 | 10.12.8.60) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-13 (52.200.223.6 | 10.12.11.165) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-12 (18.206.25.77 | 10.12.8.180) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-11 (34.237.93.103 | 10.12.8.85) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-10 (34.232.150.14 | 10.12.10.52) (shards: 7)
- longevity-parallel-topology-schema--db-node-b6114284-1 (52.1.100.31 | 10.12.10.81) (shards: 7)

OS / Image: `ami-061ef60dcbde0b09a` (aws: undefined_region)

Test: `longevity-schema-topology-changes-12h-test`
Test id: `b6114284-4647-44aa-a76e-9552e65a08eb`
Test name: `enterprise-2024.2/tier1/longevity-schema-topology-changes-12h-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-parallel-schema-changes-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/8dd85e68a1b74275e622bf8a036753ded2859bde/test-cases/longevity/longevity-parallel-schema-changes-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor b6114284-4647-44aa-a76e-9552e65a08eb`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b6114284-4647-44aa-a76e-9552e65a08eb)
- Show all stored logs command: `$ hydra investigate show-logs b6114284-4647-44aa-a76e-9552e65a08eb`

## Logs:
- **longevity-parallel-topology-schema--db-node-b6114284-3** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-3-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-3-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-6** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-6-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-6-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-7** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-7-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-7-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-9** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-9-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-9-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-8** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-8-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-8-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-1** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-1-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-1-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-2** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-2-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-2-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-4** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-4-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-4-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-10** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-10-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-10-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-5** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-5-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-5-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-12** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-12-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-12-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-17** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-17-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-17-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-16** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-16-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-16-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-14** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-14-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-14-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-11** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-11-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-11-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-15** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-15-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-15-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-21** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-21-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-21-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-23** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-23-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-23-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-24** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-24-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-24-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-19** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-19-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-19-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-26** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-26-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-26-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-13** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-13-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-13-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-25** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-25-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-25-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-18** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-18-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-18-b6114284.tar.gz)
- **longevity-parallel-topology-schema--db-node-b6114284-20** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-20-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241202_143132/longevity-parallel-topology-schema--db-node-b6114284-20-b6114284.tar.gz)
- **db-cluster-b6114284.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241203_030623/db-cluster-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241203_030623/db-cluster-b6114284.tar.gz)
- **sct-runner-events-b6114284.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241203_030623/sct-runner-events-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241203_030623/sct-runner-events-b6114284.tar.gz)
- **sct-b6114284.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241203_030623/sct-b6114284.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241203_030623/sct-b6114284.log.tar.gz)
- **loader-set-b6114284.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241203_030623/loader-set-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241203_030623/loader-set-b6114284.tar.gz)
- **monitor-set-b6114284.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241203_030623/monitor-set-b6114284.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6114284-4647-44aa-a76e-9552e65a08eb/20241203_030623/monitor-set-b6114284.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2024.2/job/tier1/job/longevity-schema-topology-changes-12h-test/11/)
[Argus](https://argus.scylladb.com/test/95f71148-1ff5-4118-8753-d6340560b071/runs?additionalRuns[]=b6114284-4647-44aa-a76e-9552e65a08eb)
</details>

**Comment by mykaul** [comment]
@timtimb0t - why do you feel it's a driver issue? Which version did you use (it's not clearly specified above) ? 
I'm not sure what do you expect the drivers team to do with this bug report.

**Comment by timtimb0t** [comment]
@mykaul , we've been talked with @piodul regarding such an error and decided to raise the issue in driver repo

**Comment by mykaul** [comment]
> [@mykaul](https://github.com/mykaul) , we've been talked with [@piodul](https://github.com/piodul) regarding such an error and it looks like driver failure so I decided to raise the issue in driver repo

OK, let's see what we end up with. If we can get to the bottom of this and figure out a driver-side issue, that'll be great. As is, I think it's a bit challenging.

**Comment by Bouncheck** [comment]
@timtimb0t Failing to connect to JMX is not a critical error. It seems you wanted to include an exception in the snippet but it's cut off.

**Comment by piodul** [comment]
@Bouncheck if you take a look into some cassandra-stress driver logs, you will notice the following tracebacks:

```
java.lang.AssertionError
        at com.datastax.driver.core.ConvictionPolicy$DefaultConvictionPolicy.signalConnectionClosed(ConvictionPolicy.java:90)
        at com.datastax.driver.core.Connection.closeAsync(Connection.java:1104)
        at com.datastax.driver.core.HostConnectionPool.discardAvailableConnections(HostConnectionPool.java:1023)
        at com.datastax.driver.core.HostConnectionPool.closeAsync(HostConnectionPool.java:984)
        at com.datastax.driver.core.SessionManager.closeAsync(SessionManager.java:196)
        at com.datastax.driver.core.Cluster$Manager.close(Cluster.java:1989)
        at com.datastax.driver.core.Cluster$Manager.access$200(Cluster.java:1560)
        at com.datastax.driver.core.Cluster.closeAsync(Cluster.java:625)
        at com.datastax.driver.core.Cluster.close(Cluster.java:636)
        at org.apache.cassandra.stress.util.JavaDriverClient.disconnect(JavaDriverClient.java:335)
        at org.apache.cassandra.stress.settings.StressSettings.disconnect(StressSettings.java:412)
        at org.apache.cassandra.stress.StressAction.run(StressAction.java:98)
        at org.apache.cassandra.stress.Stress.run(Stress.java:151)
        at org.apache.cassandra.stress.Stress.main(Stress.java:70)
```

Grep for the "java.lang.AssertionError" string.

**Comment by piodul** [comment]
Perhaps a duplicate of https://github.com/scylladb/java-driver/issues/82?
