### ISSUE TITLE
Unexpected ERROR response message from server to a OPTIONS message

### ISSUE THREAD

**Issue by fggarcia** [scylladb/java-driver#62]
After upgrade to scylla-java-driver 3.10.2-scylla-0 (from 3.10.1-scylla-0) 

Java version: java11
Scylla version: 4.3.0

```
Exception in thread "main" com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried:scylla-00/10.194.120.254:19042 (com.datastax.driver.core.exceptions.TransportException: [scylla-00/xxxxxxxx:9042] Unexpected ERROR response message from server to a OPTIONS message),scylla-01/xxxxxxxx:19042 (com.datastax.driver.core.exceptions.TransportException: [scylla-01/xxxxxxxx:9042] Unexpected ERROR response message from server to a OPTIONS message), scylla-02/xxxxxxxx:9042 (com.datastax.driver.core.exceptions.TransportException: [scylla-02/xxxxxxxx:9042] Unexpected ERROR response message from server to a OPTIONS message))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:270)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:109)
	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1843)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1756)
	at com.datastax.driver.core.Cluster.init(Cluster.java:218)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:391)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:370)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:315)

```

Rollback to version 3.10.1-scylla-0 resolve issue.

How i can help you?

**Comment by avelanarius** [comment]
@fggarcia Could you provide more details on the connection?
 - What type of authentication/authorization are you using? (if any)
 - How do you specify contact points? (by "raw" IP adresses, by hostnames?)
 - Are the Java Driver client and Scylla cluster in the same network? (for example if it was running on AWS, whether they are in the same VPC, subnet)

**Comment by fggarcia** [comment]
Hi @avelanarius 

```
What type of authentication/authorization are you using? (if any) -> 
```
scylla.yaml
authenticator: PasswordAuthenticator
authorizer: CassandraAuthorizer

app
val authProvider = new PlainTextAuthProvider(config.user, config.pass)

  val keyspaceBuilder = ContactPoints(config.seeds, config.port)
    .withClusterBuilder(clusterBuilder =>
      clusterBuilder
        .withClusterName(config.cluster)
        .withCompression(ProtocolOptions.Compression.LZ4)
        .withProtocolVersion(ProtocolVersion.NEWEST_SUPPORTED)
        .withLoadBalancingPolicy(
          new TokenAwarePolicy(DCAwareRoundRobinPolicy.builder.withLocalDc(config.datacenter).build)
        )
        .withRetryPolicy(new LoggingRetryPolicy(DowngradingConsistencyRetryPolicy.INSTANCE))
        .withReconnectionPolicy(new ConstantReconnectionPolicy(config.reconnectionTimeMs))
        .withAuthProvider(authProvider))

  val connector = keyspaceBuilder.keySpace(config.keyspace)

```
How do you specify contact points? (by "raw" IP adresses, by hostnames?) ->
```
by hostnames

```
Are the Java Driver client and Scylla cluster in the same network? (for example if it was running on AWS, whether they are in the same VPC, subnet)
```
yes, we don't use AWS. We use owner local network

**Comment by avelanarius** [comment]
Thank you for the details. I am now able to reproduce the issue.

It turned out that turning compression (LZ4) caused problems in the newer version of the library. I have located the root cause, so the fix will come relatively soon.

For now I suggest rolling back to `3.10.1-scylla-0` (as you already did). A new version of the library with the fix should come within a week.

**Comment by fggarcia** [comment]
Thanks @avelanarius 

Only one more comment. When i tried in local environment with docker-compose (one scylla instance), the issue didn't occurred, only when i deployed in beta environment (3 scylla instances)

**Comment by fggarcia** [comment]
Hi @avelanarius thanks you!

last release resolve the issue. Close this.
