### ISSUE TITLE
c-s equiped with shard-aware dirver can fail with AssertionError that comes from closeAsync

### ISSUE THREAD

**Issue by dkropachev** [scylladb/java-driver#82]
When test is completed c-s closes connection to the cluster.
due to the bug in driver it can fail there with assertException:

```
java.lang.AssertionError
at com.datastax.driver.core.ConvictionPolicy$DefaultConvictionPolicy.signalConnectionClosed(ConvictionPolicy.java:90)
at com.datastax.driver.core.Connection.closeAsync(Connection.java:953)
at com.datastax.driver.core.HostConnectionPool.discardAvailableConnections(HostConnectionPool.java:882)
at com.datastax.driver.core.HostConnectionPool.closeAsync(HostConnectionPool.java:843)
```

**Comment by haaawk** [comment]
Do you have reproducer @dkropachev ? Is the error thrown on every cluster.close()?

**Comment by haaawk** [comment]
Also what version of the driver is this?

**Comment by dkropachev** [comment]
> Do you have reproducer @dkropachev ? Is the error thrown on every cluster.close()?

Have no way to reproduce it.
This error is thrown once after which c-s goes to panic

> Also what version of the driver is this?

No reliable information on that, test run where it happened is lost, but most likely it was scylla-driver-core-3.10.1-scylla-0-shaded

**Comment by dkropachev** [comment]
Most likely this exception comes from this:


When connection is closed it find host it is relates to by EndPoint in manager metadata, 

```
src/main/java/com/datastax/driver/core/Connection.java:957  
    if (signaled.compareAndSet(false, true)) {
      Host host = getHost();
      if (host != null) {
        host.convictionPolicy.signalConnectionClosed(this);
      }
    }


src/main/java/com/datastax/driver/core/Connection.java:988  
  private Host getHost() {
    Metadata metadata = factory.manager.metadata;
    Host host = metadata.getHost(endPoint);
    // During init the host might not be in metatada.hosts yet, try the contact points
    if (host == null) {
      host = metadata.getContactPoint(endPoint);
    }
    return host;
  }


src/main/java/com/datastax/driver/core/Metadata.java:202
  Host getHost(EndPoint endPoint) {
    for (Host host : hosts.values()) {
      if (host.getEndPoint().equals(endPoint)) {
        return host;
      }
    }
    return null;
  }

```

There are two of three exiting  Endpoit implementations that are overriding equals in a way that allows different instances of Endpoints to match:

```
src/main/java/com/datastax/driver/core/TranslatedAddressEndPoint.java:39
  public boolean equals(Object other) {
    if (other == this) {
      return true;
    } else if (other instanceof TranslatedAddressEndPoint) {
      TranslatedAddressEndPoint that = (TranslatedAddressEndPoint) other;
      return Objects.equal(this.translatedAddress, that.translatedAddress);
    } else {
      return false;
    }
  }

src/main/java/com/datastax/driver/core/SniEndPoint.java:80
  @Override
  public boolean equals(Object other) {
    if (other == this) {
      return true;
    } else if (other instanceof SniEndPoint) {
      SniEndPoint that = (SniEndPoint) other;
      return this.proxyAddress.equals(that.proxyAddress) && this.serverName.equals(that.serverName);
    } else {
      return false;
    }
  }

``` 

So, most likely this issue happens when connection was initialized on one host instance, and closed on another.

**Comment by haaawk** [comment]
> > Do you have reproducer @dkropachev ? Is the error thrown on every cluster.close()?
> 
> Have no way to reproduce it.
> This error is thrown once after which c-s goes to panic
>  

What does it mean for c-s to go panic? @dkropachev

**Comment by haaawk** [comment]
> 
> There are two of three exiting Endpoit implementations that are overriding equals in a way that allows different instances of Endpoints to match:
> 
> ```
> src/main/java/com/datastax/driver/core/TranslatedAddressEndPoint.java:39
>   public boolean equals(Object other) {
>     if (other == this) {
>       return true;
>     } else if (other instanceof TranslatedAddressEndPoint) {
>       TranslatedAddressEndPoint that = (TranslatedAddressEndPoint) other;
>       return Objects.equal(this.translatedAddress, that.translatedAddress);
>     } else {
>       return false;
>     }
>   }
> 
> src/main/java/com/datastax/driver/core/SniEndPoint.java:80
>   @Override
>   public boolean equals(Object other) {
>     if (other == this) {
>       return true;
>     } else if (other instanceof SniEndPoint) {
>       SniEndPoint that = (SniEndPoint) other;
>       return this.proxyAddress.equals(that.proxyAddress) && this.serverName.equals(that.serverName);
>     } else {
>       return false;
>     }
>   }
> ```

They actually don't match according to the implementations of equals they provide.

**Comment by dkropachev** [comment]
> > > Do you have reproducer @dkropachev ? Is the error thrown on every cluster.close()?
> > 
> > Have no way to reproduce it.
> > This error is thrown once after which c-s goes to panic
> >  
> 
> What does it mean for c-s to go panic? @dkropachev 
> 

It means that it immediately stops process execution due to the unhandled exception

**Comment by haaawk** [comment]
> > > > Do you have reproducer @dkropachev ? Is the error thrown on every cluster.close()?
> > > 
> > > 
> > > Have no way to reproduce it.
> > > This error is thrown once after which c-s goes to panic
> > 
> > 
> > What does it mean for c-s to go panic? @dkropachev
> 
> It means that it immediately stops process execution due to the unhandled exception

You mean it retries a request 10 times and after no success c-s fails - is that correct?

**Comment by dkropachev** [comment]
> 
> > 
> > There are two of three exiting Endpoit implementations that are overriding equals in a way that allows different instances of Endpoints to match:
> > 
> > ```
> > src/main/java/com/datastax/driver/core/TranslatedAddressEndPoint.java:39
> >   public boolean equals(Object other) {
> >     if (other == this) {
> >       return true;
> >     } else if (other instanceof TranslatedAddressEndPoint) {
> >       TranslatedAddressEndPoint that = (TranslatedAddressEndPoint) other;
> >       return Objects.equal(this.translatedAddress, that.translatedAddress);
> >     } else {
> >       return false;
> >     }
> >   }
> > 
> > src/main/java/com/datastax/driver/core/SniEndPoint.java:80
> >   @Override
> >   public boolean equals(Object other) {
> >     if (other == this) {
> >       return true;
> >     } else if (other instanceof SniEndPoint) {
> >       SniEndPoint that = (SniEndPoint) other;
> >       return this.proxyAddress.equals(that.proxyAddress) && this.serverName.equals(that.serverName);
> >     } else {
> >       return false;
> >     }
> >   }
> > ```
> 
> They actually don't match according to the implementations of equals they provide.
> 

Not quite sure what it means.

**Comment by haaawk** [comment]
> > There are two of three exiting Endpoit implementations that are overriding equals in a way that allows different instances of Endpoints to match:
> > ```
> > src/main/java/com/datastax/driver/core/TranslatedAddressEndPoint.java:39
> >   public boolean equals(Object other) {
> >     if (other == this) {
> >       return true;
> >     } else if (other instanceof TranslatedAddressEndPoint) {
> >       TranslatedAddressEndPoint that = (TranslatedAddressEndPoint) other;
> >       return Objects.equal(this.translatedAddress, that.translatedAddress);
> >     } else {
> >       return false;
> >     }
> >   }
> > 
> > src/main/java/com/datastax/driver/core/SniEndPoint.java:80
> >   @Override
> >   public boolean equals(Object other) {
> >     if (other == this) {
> >       return true;
> >     } else if (other instanceof SniEndPoint) {
> >       SniEndPoint that = (SniEndPoint) other;
> >       return this.proxyAddress.equals(that.proxyAddress) && this.serverName.equals(that.serverName);
> >     } else {
> >       return false;
> >     }
> >   }
> > ```
> 
> They actually don't match according to the implementations of equals they provide.

I don't think that's the problem. Since getHost compares using equals and different implementations of EndPoint never `equal`.

**Comment by dkropachev** [comment]
> > > > > Do you have reproducer @dkropachev ? Is the error thrown on every cluster.close()?
> > > > 
> > > > 
> > > > Have no way to reproduce it.
> > > > This error is thrown once after which c-s goes to panic
> > > 
> > > 
> > > What does it mean for c-s to go panic? @dkropachev
> > 
> > It means that it immediately stops process execution due to the unhandled exception
> 
> You mean it retries a request 10 times and after no success c-s fails - is that correct?

No, it stop execution right away, at least in the case that is reffed here

**Comment by haaawk** [comment]
> > > > > > Do you have reproducer @dkropachev ? Is the error thrown on every cluster.close()?
> > > > > 
> > > > > 
> > > > > Have no way to reproduce it.
> > > > > This error is thrown once after which c-s goes to panic
> > > > 
> > > > 
> > > > What does it mean for c-s to go panic? @dkropachev
> > > 
> > > 
> > > It means that it immediately stops process execution due to the unhandled exception
> > 
> > 
> > You mean it retries a request 10 times and after no success c-s fails - is that correct?
> 
> No, it stop execution right away, at least in the case that is reffed here

What's the exception that causes it to stop?

**Comment by haaawk** [comment]
> > > There are two of three exiting Endpoit implementations that are overriding equals in a way that allows different instances of Endpoints to match:
> > > ```
> > > src/main/java/com/datastax/driver/core/TranslatedAddressEndPoint.java:39
> > >   public boolean equals(Object other) {
> > >     if (other == this) {
> > >       return true;
> > >     } else if (other instanceof TranslatedAddressEndPoint) {
> > >       TranslatedAddressEndPoint that = (TranslatedAddressEndPoint) other;
> > >       return Objects.equal(this.translatedAddress, that.translatedAddress);
> > >     } else {
> > >       return false;
> > >     }
> > >   }
> > > 
> > > src/main/java/com/datastax/driver/core/SniEndPoint.java:80
> > >   @Override
> > >   public boolean equals(Object other) {
> > >     if (other == this) {
> > >       return true;
> > >     } else if (other instanceof SniEndPoint) {
> > >       SniEndPoint that = (SniEndPoint) other;
> > >       return this.proxyAddress.equals(that.proxyAddress) && this.serverName.equals(that.serverName);
> > >     } else {
> > >       return false;
> > >     }
> > >   }
> > > ```
> > 
> > 
> > They actually don't match according to the implementations of equals they provide.
> 
> Not quite sure what it means.

It means that it one host in metadata represented by TranslatedAddressEndPoint is removed and readded using SniEndPoint, getHost(Endpoint) called with TranslatedAddressEndPoint won't find it and if it was true the code wouldn't ever enter `at com.datastax.driver.core.Connection.closeAsync(Connection.java:953)` because there's an if checking for host to be null before it.

**Comment by dkropachev** [comment]
> > > > There are two of three exiting Endpoit implementations that are overriding equals in a way that allows different instances of Endpoints to match:
> > > > ```
> > > > src/main/java/com/datastax/driver/core/TranslatedAddressEndPoint.java:39
> > > >   public boolean equals(Object other) {
> > > >     if (other == this) {
> > > >       return true;
> > > >     } else if (other instanceof TranslatedAddressEndPoint) {
> > > >       TranslatedAddressEndPoint that = (TranslatedAddressEndPoint) other;
> > > >       return Objects.equal(this.translatedAddress, that.translatedAddress);
> > > >     } else {
> > > >       return false;
> > > >     }
> > > >   }
> > > > 
> > > > src/main/java/com/datastax/driver/core/SniEndPoint.java:80
> > > >   @Override
> > > >   public boolean equals(Object other) {
> > > >     if (other == this) {
> > > >       return true;
> > > >     } else if (other instanceof SniEndPoint) {
> > > >       SniEndPoint that = (SniEndPoint) other;
> > > >       return this.proxyAddress.equals(that.proxyAddress) && this.serverName.equals(that.serverName);
> > > >     } else {
> > > >       return false;
> > > >     }
> > > >   }
> > > > ```
> > > 
> > > 
> > > They actually don't match according to the implementations of equals they provide.
> > 
> > Not quite sure what it means.
> 
> It means that it one host in metadata represented by TranslatedAddressEndPoint is removed and readded using SniEndPoint, getHost(Endpoint) called with TranslatedAddressEndPoint won't find it and if it was true the code wouldn't ever enter `at com.datastax.driver.core.Connection.closeAsync(Connection.java:953)` because there's an if checking for host to be null before it.

Why it would be added with deferent class ?

**Comment by dkropachev** [comment]
> > > > > > > Do you have reproducer @dkropachev ? Is the error thrown on every cluster.close()?
> > > > > > 
> > > > > > 
> > > > > > Have no way to reproduce it.
> > > > > > This error is thrown once after which c-s goes to panic
> > > > > 
> > > > > 
> > > > > What does it mean for c-s to go panic? @dkropachev
> > > > 
> > > > 
> > > > It means that it immediately stops process execution due to the unhandled exception
> > > 
> > > 
> > > You mean it retries a request 10 times and after no success c-s fails - is that correct?
> > 
> > No, it stop execution right away, at least in the case that is reffed here
> 
> What's the exception that causes it to stop?

It is in the name of the issue

**Comment by haaawk** [comment]
> > > > > There are two of three exiting Endpoit implementations that are overriding equals in a way that allows different instances of Endpoints to match:
> > > > > ```
> > > > > src/main/java/com/datastax/driver/core/TranslatedAddressEndPoint.java:39
> > > > >   public boolean equals(Object other) {
> > > > >     if (other == this) {
> > > > >       return true;
> > > > >     } else if (other instanceof TranslatedAddressEndPoint) {
> > > > >       TranslatedAddressEndPoint that = (TranslatedAddressEndPoint) other;
> > > > >       return Objects.equal(this.translatedAddress, that.translatedAddress);
> > > > >     } else {
> > > > >       return false;
> > > > >     }
> > > > >   }
> > > > > 
> > > > > src/main/java/com/datastax/driver/core/SniEndPoint.java:80
> > > > >   @Override
> > > > >   public boolean equals(Object other) {
> > > > >     if (other == this) {
> > > > >       return true;
> > > > >     } else if (other instanceof SniEndPoint) {
> > > > >       SniEndPoint that = (SniEndPoint) other;
> > > > >       return this.proxyAddress.equals(that.proxyAddress) && this.serverName.equals(that.serverName);
> > > > >     } else {
> > > > >       return false;
> > > > >     }
> > > > >   }
> > > > > ```
> > > > 
> > > > 
> > > > They actually don't match according to the implementations of equals they provide.
> > > 
> > > 
> > > Not quite sure what it means.
> > 
> > 
> > It means that it one host in metadata represented by TranslatedAddressEndPoint is removed and readded using SniEndPoint, getHost(Endpoint) called with TranslatedAddressEndPoint won't find it and if it was true the code wouldn't ever enter `at com.datastax.driver.core.Connection.closeAsync(Connection.java:953)` because there's an if checking for host to be null before it.
> 
> Why it would be added with deferent class ?

I don't know - it was your hypotesis that different implementations of the EndPoint interface can be a problem. I'm just saying that this is likely not the problem here.

**Comment by haaawk** [comment]
> > > > > > > > Do you have reproducer @dkropachev ? Is the error thrown on every cluster.close()?
> > > > > > > 
> > > > > > > 
> > > > > > > Have no way to reproduce it.
> > > > > > > This error is thrown once after which c-s goes to panic
> > > > > > 
> > > > > > 
> > > > > > What does it mean for c-s to go panic? @dkropachev
> > > > > 
> > > > > 
> > > > > It means that it immediately stops process execution due to the unhandled exception
> > > > 
> > > > 
> > > > You mean it retries a request 10 times and after no success c-s fails - is that correct?
> > > 
> > > 
> > > No, it stop execution right away, at least in the case that is reffed here
> > 
> > 
> > What's the exception that causes it to stop?
> 
> It is in the name of the issue

Ok but in what scenarios does it happen? It will be hard to do anything here unless we can reliably reproduce the problem. Do you see this regularly or is it a one-off?

**Comment by dkropachev** [comment]
> > > > > > There are two of three exiting Endpoit implementations that are overriding equals in a way that allows different instances of Endpoints to match:
> > > > > > ```
> > > > > > src/main/java/com/datastax/driver/core/TranslatedAddressEndPoint.java:39
> > > > > >   public boolean equals(Object other) {
> > > > > >     if (other == this) {
> > > > > >       return true;
> > > > > >     } else if (other instanceof TranslatedAddressEndPoint) {
> > > > > >       TranslatedAddressEndPoint that = (TranslatedAddressEndPoint) other;
> > > > > >       return Objects.equal(this.translatedAddress, that.translatedAddress);
> > > > > >     } else {
> > > > > >       return false;
> > > > > >     }
> > > > > >   }
> > > > > > 
> > > > > > src/main/java/com/datastax/driver/core/SniEndPoint.java:80
> > > > > >   @Override
> > > > > >   public boolean equals(Object other) {
> > > > > >     if (other == this) {
> > > > > >       return true;
> > > > > >     } else if (other instanceof SniEndPoint) {
> > > > > >       SniEndPoint that = (SniEndPoint) other;
> > > > > >       return this.proxyAddress.equals(that.proxyAddress) && this.serverName.equals(that.serverName);
> > > > > >     } else {
> > > > > >       return false;
> > > > > >     }
> > > > > >   }
> > > > > > ```
> > > > > 
> > > > > 
> > > > > They actually don't match according to the implementations of equals they provide.
> > > > 
> > > > 
> > > > Not quite sure what it means.
> > > 
> > > 
> > > It means that it one host in metadata represented by TranslatedAddressEndPoint is removed and readded using SniEndPoint, getHost(Endpoint) called with TranslatedAddressEndPoint won't find it and if it was true the code wouldn't ever enter `at com.datastax.driver.core.Connection.closeAsync(Connection.java:953)` because there's an if checking for host to be null before it.
> > 
> > 
> > Why it would be added with deferent class ?
> 
> I don't know - it was your hypotesis that different implementations of the EndPoint interface can be a problem. I'm just saying that this is likely not the problem here.

My hypotesis
> So, most likely this issue happens when connection was initialized on one host instance, and closed on another.

Clearly refers to instance, not a class

**Comment by dkropachev** [comment]
> > > > > > > > > Do you have reproducer @dkropachev ? Is the error thrown on every cluster.close()?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Have no way to reproduce it.
> > > > > > > > This error is thrown once after which c-s goes to panic
> > > > > > > 
> > > > > > > 
> > > > > > > What does it mean for c-s to go panic? @dkropachev
> > > > > > 
> > > > > > 
> > > > > > It means that it immediately stops process execution due to the unhandled exception
> > > > > 
> > > > > 
> > > > > You mean it retries a request 10 times and after no success c-s fails - is that correct?
> > > > 
> > > > 
> > > > No, it stop execution right away, at least in the case that is reffed here
> > > 
> > > 
> > > What's the exception that causes it to stop?
> > 
> > 
> > It is in the name of the issue
> 
> Ok but in what scenarios does it happen? It will be hard to do anything here unless we can reliably reproduce the problem. Do you see this regularly or is it a one-off?

As it was mentioned, unfortunatelly no exact scenario exists at this point, but proposed scenario is that something triggered host removing from cluster metadata and it's reinitiation, while connection was alive, after host was initiated and added to metadata, connection was closed on newly created host instance, which trigered this assertion.

**Comment by haaawk** [comment]
> > > > > > > > > > Do you have reproducer @dkropachev ? Is the error thrown on every cluster.close()?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Have no way to reproduce it.
> > > > > > > > > This error is thrown once after which c-s goes to panic
> > > > > > > > 
> > > > > > > > 
> > > > > > > > What does it mean for c-s to go panic? @dkropachev
> > > > > > > 
> > > > > > > 
> > > > > > > It means that it immediately stops process execution due to the unhandled exception
> > > > > > 
> > > > > > 
> > > > > > You mean it retries a request 10 times and after no success c-s fails - is that correct?
> > > > > 
> > > > > 
> > > > > No, it stop execution right away, at least in the case that is reffed here
> > > > 
> > > > 
> > > > What's the exception that causes it to stop?
> > > 
> > > 
> > > It is in the name of the issue
> > 
> > 
> > Ok but in what scenarios does it happen? It will be hard to do anything here unless we can reliably reproduce the problem. Do you see this regularly or is it a one-off?
> 
> As it was mentioned, unfortunatelly no exact scenario exists at this point, but proposed scenario is that something triggered host removing from cluster metadata and it's reinitiation, while connection was alive, after host was initiated and added to metadata, connection was closed on newly created host instance, which trigered this assertion.

I will ask again:
1. Have you experienced this only one time or few times?
2. What were you doing when you experienced the problem? You may not have a reliable reproducer but you must have been doing something when the problem occured. Even when the conditions don't guarantee the reproduction of the problem, they may give some clue.

**Comment by dkropachev** [comment]
> > > > > > > > > > > Do you have reproducer @dkropachev ? Is the error thrown on every cluster.close()?
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Have no way to reproduce it.
> > > > > > > > > > This error is thrown once after which c-s goes to panic
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > What does it mean for c-s to go panic? @dkropachev
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It means that it immediately stops process execution due to the unhandled exception
> > > > > > > 
> > > > > > > 
> > > > > > > You mean it retries a request 10 times and after no success c-s fails - is that correct?
> > > > > > 
> > > > > > 
> > > > > > No, it stop execution right away, at least in the case that is reffed here
> > > > > 
> > > > > 
> > > > > What's the exception that causes it to stop?
> > > > 
> > > > 
> > > > It is in the name of the issue
> > > 
> > > 
> > > Ok but in what scenarios does it happen? It will be hard to do anything here unless we can reliably reproduce the problem. Do you see this regularly or is it a one-off?
> > 
> > As it was mentioned, unfortunatelly no exact scenario exists at this point, but proposed scenario is that something triggered host removing from cluster metadata and it's reinitiation, while connection was alive, after host was initiated and added to metadata, connection was closed on newly created host instance, which trigered this assertion.
> 
> I will ask again:
> 1. Have you experienced this only one time or few times?
> 2. What were you doing when you experienced the problem? You may not have a reliable reproducer but you must have been doing something when the problem occured. Even when the conditions don't guarantee the reproduction of the problem, they may give some clue.

1. At this point I aware of only one such incident
2. The test was full of everything, resharding, node restarts, node replacing.

**Comment by haaawk** [comment]
> > > > > > > > > > > > Do you have reproducer @dkropachev ? Is the error thrown on every cluster.close()?
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > Have no way to reproduce it.
> > > > > > > > > > > This error is thrown once after which c-s goes to panic
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > What does it mean for c-s to go panic? @dkropachev
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > It means that it immediately stops process execution due to the unhandled exception
> > > > > > > > 
> > > > > > > > 
> > > > > > > > You mean it retries a request 10 times and after no success c-s fails - is that correct?
> > > > > > > 
> > > > > > > 
> > > > > > > No, it stop execution right away, at least in the case that is reffed here
> > > > > > 
> > > > > > 
> > > > > > What's the exception that causes it to stop?
> > > > > 
> > > > > 
> > > > > It is in the name of the issue
> > > > 
> > > > 
> > > > Ok but in what scenarios does it happen? It will be hard to do anything here unless we can reliably reproduce the problem. Do you see this regularly or is it a one-off?
> > > 
> > > 
> > > As it was mentioned, unfortunatelly no exact scenario exists at this point, but proposed scenario is that something triggered host removing from cluster metadata and it's reinitiation, while connection was alive, after host was initiated and added to metadata, connection was closed on newly created host instance, which trigered this assertion.
> > 
> > 
> > I will ask again:
> > 
> > 1. Have you experienced this only one time or few times?
> > 2. What were you doing when you experienced the problem? You may not have a reliable reproducer but you must have been doing something when the problem occured. Even when the conditions don't guarantee the reproduction of the problem, they may give some clue.
> 
> 1. At this point I aware of only one such incident

Thanks.

> 2. The test was full of everything, resharding, node restarts, node replacing.

Was it SCT?

**Comment by dkropachev** [comment]
> > > > > > > > > > > > > Do you have reproducer @dkropachev ? Is the error thrown on every cluster.close()?
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > Have no way to reproduce it.
> > > > > > > > > > > > This error is thrown once after which c-s goes to panic
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > What does it mean for c-s to go panic? @dkropachev
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > It means that it immediately stops process execution due to the unhandled exception
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > You mean it retries a request 10 times and after no success c-s fails - is that correct?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > No, it stop execution right away, at least in the case that is reffed here
> > > > > > > 
> > > > > > > 
> > > > > > > What's the exception that causes it to stop?
> > > > > > 
> > > > > > 
> > > > > > It is in the name of the issue
> > > > > 
> > > > > 
> > > > > Ok but in what scenarios does it happen? It will be hard to do anything here unless we can reliably reproduce the problem. Do you see this regularly or is it a one-off?
> > > > 
> > > > 
> > > > As it was mentioned, unfortunatelly no exact scenario exists at this point, but proposed scenario is that something triggered host removing from cluster metadata and it's reinitiation, while connection was alive, after host was initiated and added to metadata, connection was closed on newly created host instance, which trigered this assertion.
> > > 
> > > 
> > > I will ask again:
> > > 
> > > 1. Have you experienced this only one time or few times?
> > > 2. What were you doing when you experienced the problem? You may not have a reliable reproducer but you must have been doing something when the problem occured. Even when the conditions don't guarantee the reproduction of the problem, they may give some clue.
> > 
> > 1. At this point I aware of only one such incident
> 
> Thanks.
> 
> > 2. The test was full of everything, resharding, node restarts, node replacing.
> 
> Was it SCT?

Yes, it was sct

**Comment by dkropachev** [comment]
Fixed [here](https://github.com/scylladb/java-driver/pull/466)
