### ISSUE TITLE
java.lang.NullPointerException: Cannot read the array length because "<local2>" is null

### ISSUE THREAD

**Issue by dkropachev** [scylladb/java-driver#85]
Faced this issue once while playing with nosqlbench:

```
[cluster1-worker-0] ERROR com.datastax.cql3.scylla_shaded.driver.core.ExceptionCatchingRunnable - Unexpected error while executing task
java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
    at com.datastax.cql3.scylla_shaded.driver.core.HostConnectionPool.closeAsync(HostConnectionPool.java:841)
    at com.datastax.cql3.scylla_shaded.driver.core.SessionManager.removePool(SessionManager.java:440)
    at com.datastax.cql3.scylla_shaded.driver.core.SessionManager.onDown(SessionManager.java:528)
    at com.datastax.cql3.scylla_shaded.driver.core.Cluster$Manager.onDown(Cluster.java:2207)
    at com.datastax.cql3.scylla_shaded.driver.core.Cluster$Manager.access$1200(Cluster.java:1560)
    at com.datastax.cql3.scylla_shaded.driver.core.Cluster$Manager$5.runMayThrow(Cluster.java:2162)
    at com.datastax.cql3.scylla_shaded.driver.core.ExceptionCatchingRunnable.run(ExceptionCatchingRunnable.java:32)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at com.datastax.internal.com_google_common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
    at com.datastax.internal.com_google_common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
    at com.datastax.internal.com_google_common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:832)
[cqltabular2_default_schema:001] WARN com.datastax.cql3.scylla_shaded.driver.core.Session - Error creating pool to /10.0.2.65:9042
com.datastax.cql3.scylla_shaded.driver.core.exceptions.OperationTimedOutException: [/10.0.2.65:9042] Operation timed out
    at com.datastax.cql3.scylla_shaded.driver.core.Connection$Future.onTimeout(Connection.java:1642)
    at com.datastax.cql3.scylla_shaded.driver.core.Connection$ResponseHandler$1.run(Connection.java:1721)
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by dkropachev** [comment]
Problem goes from src/main/java/com/datastax/driver/core/HostConnectionPool.java:

We have 5 attributes that needs to be initialized before being used:  
```
  List<Connection>[] connections;
  private AtomicInteger[] open;
  @VisibleForTesting Set<Connection>[] trash;
  private Queue<PendingBorrow>[] pendingBorrows;
  private AtomicInteger[] scheduledForCreation;
``` 

But we initialize them only at HostConnectionPool.initAsyncWithConnection , which may not happen due to the exception escaping at HostConnectionPool.initAsync:
```
  ListenableFuture<Void> initAsync(Connection reusedConnection) {
    if (reusedConnection != null && reusedConnection.setOwner(this)) {
      return initAsyncWithConnection(reusedConnection);
    }
    try {
      return initAsyncWithConnection(manager.connectionFactory().open(this));
    } catch (Exception e) {
      phase.compareAndSet(Phase.INITIALIZING, Phase.INIT_FAILED);
      SettableFuture<Void> future = SettableFuture.create();
      future.setException(e);
      return future;
    }
  }
```

So basically when initial connection fails we end up with perfectly uninitialized instance

**Comment by dkropachev** [comment]
Another occurrence on `scylla-driver-core 3.11.5.11`, seen in Scylla Jenkins on March 29, 2026:

Build: https://jenkins.scylladb.com/job/scylla-master/job/dtest-debug/558/
Failing test: https://jenkins.scylladb.com/job/scylla-master/job/dtest-debug/558/testReport/junit/replace_address_test/TestReplaceAddress/Run_Dtest_Parallel_Cloud_Machines___Dtest___full_split005___test_replace_with_background_workload_rbo_enabled_/

Relevant stack:
```text
ERROR [cluster1-worker-0] 2026-03-29 08:54:49,544 ExceptionCatchingRunnable.java:36 - Unexpected error while executing task
java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
    at com.datastax.driver.core.HostConnectionPool.discardAvailableConnections(HostConnectionPool.java:1016)
    at com.datastax.driver.core.HostConnectionPool.closeAsync(HostConnectionPool.java:987)
    at com.datastax.driver.core.SessionManager.removePool(SessionManager.java:446)
    at com.datastax.driver.core.SessionManager.onDown(SessionManager.java:534)
    at com.datastax.driver.core.Cluster$Manager.onDown(Cluster.java:2165)
```

The surrounding log shows topology churn during node replacement:
- `/127.0.71.3:9042` is discovered and then goes down
- pool creation to `/127.0.71.3:9042` fails with `Connection refused`
- host-down cleanup then goes through `removePool -> closeAsync -> discardAvailableConnections`

The same run also shows:
```text
WARN  [main] ... Error creating pool to /127.0.71.3:9042
com.datastax.driver.core.exceptions.TransportException: [/127.0.71.3:9042] Cannot connect
Caused by: java.net.ConnectException: Connection refused
```

This matches the analysis already described here: if the initial pool connection fails before `initAsyncWithConnection()` initializes `connections` / `trash`, then `closeAsync()` can NPE on cleanup.

In this Jenkins run the test ultimately failed for a separate `cassandra-stress` schema/rack issue, so this looks like a secondary driver crash rather than the primary failure, but it is still reproducible noise from real topology changes.

**Comment by dkropachev** [comment]
Created Jira tracking item for this issue: https://scylladb.atlassian.net/browse/DRIVER-757

Current status from the investigation:
- This is the same pool-close race during initialization: host-down cleanup can call `SessionManager.removePool()` on a `HostConnectionPool` whose shard structures were not fully initialized, and `closeAsync()` then reaches `discardAvailableConnections()` with null or partially populated arrays.
- The fix is already merged in https://github.com/scylladb/java-driver/pull/864 (`3e441942c41d9052b457fa173f582b2f54a7725b`) on `scylla-3.x`.
- The regression coverage is `HostConnectionPoolTest.should_close_uninitialized_pool_without_npe`.

**Comment by dkropachev** [comment]
Was fixed at https://github.com/scylladb/java-driver/pull/864
