### ISSUE TITLE
Potential unclosed sessions in integration tests on branch 3.x

### ISSUE THREAD

**Issue by avelanarius** [scylladb/java-driver#97]
When running integration tests (introduced in #94), there are lots of exceptions of this type:

```
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.1.2:36073
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:225)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:291)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Although they don't affect the tests correctly running, those types of exceptions don't appear in the upstream repo. It seems that for some reason sessions from previous tests are not correctly closed (the IP+port refers to a CCM cluster that is already stopped).

**Comment by roydahan** [comment]
Closing as too old issue.
